import type { Metadata } from "next";
import { Figtree, Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const figtree = Figtree({
  variable: "--font-figtree",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${figtree.className} antialiased`}
      >
        {children}
        <Toaster
          theme="light"
          richColors
          toastOptions={{
            unstyled: true,
            classNames: {
              toast:
                "group flex items-center gap-2 w-[350px] p-5 rounded-[24px] bg-white/80 backdrop-blur-2xl border border-white shadow-[0_20px_50px_rgba(0,0,0,0.1)] ring-1 ring-black/5",
              title: "text-[16px] font-bold text-slate-900 tracking-tight",
              description:
                "text-[14px] text-slate-600 font-medium leading-tight",
              icon: "flex-shrink-0 scale-125 mr-1",
            },
          }}
        />
      </body>
    </html>
  );
}
